function [fitresult, gof] = createSineFit(x, y, doPlot)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Sinefit' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jul-2021 20:21:57


%% Fit: 'Sinefit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.Normalize = 'on';
opts.StartPoint = [(max(y)-min(y))/2 2*pi -pi/2];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if doPlot
    % Plot fit with data.
    figure( 'Name', 'Sinefit' );
    h = plot( fitresult, xData, yData );
    legend( h, 'y vs. x', 'Sinefit', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'x', 'Interpreter', 'none' );
    ylabel( 'y', 'Interpreter', 'none' );
    grid on
end


